version: '2.1'

services:

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root

    image: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - /home/eduard/Desktop/finall_project/configuration/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping", "-h", "mysql" ]
      timeout: 1s
      retries: 20

  vk_mock:
    image: 'vk_mock'
    build: ./mock

  myapp:
    image: "myapp"
    volumes:
      - /home/eduard/Desktop/finall_project/configuration/config:/tmp/conf
    ports:
      - "8081:8081"
    entrypoint: "/app/myapp --config=/tmp/conf"
    depends_on:
      mysql:
        condition: service_healthy
      vk_mock:
        condition: service_started



